[project]
name = "basics"
version = "0.0.0"
description = "CS336 assignment 1: Basics"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "regex>=2026.7.19",
]

[project.scripts]
main = "basics:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
